FinTechApp/Controllers/TransactionController.cs
using FinTech_App.Dto;
using FinTech_App.Model;
using FinTechApp.Communication;
using FinTechApp.dto;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace FinTechApp.Controllers;

public class TransactionController : Controller
{
    private readonly ITransactionService _transactionService;
    private readonly IClientDataService _clientService;

    public TransactionController (ITransactionService transactionService, IClientDataService clientDataService)
    {
        _transactionService = transactionService;
        _clientService = clientDataService;
    }


    public async Task<IActionResult> Index()
    {
        var transactions = await _transactionService.GetTransactionAsync();
        return View(transactions);
    }

    public async Task< IActionResult> CreateTransaction() 
    {
        var clients = await _clientService.GetClientsAsync();
        var accounts = await _clientService.GetAccountsAsync();
        return View(
                new TransactionViewDto
                {
                    Accounts = accounts.Select(
                      account => new SelectListItem
                        {
                            Text = account.Name,
                            Value = account.Id.ToString()
                        }).ToList(),
                    Clients = clients.Select(
                        client => new SelectListItem 
                        { 
                            Text=client.Name,
                            Value = client.Id.ToString()
                        }).ToList(),
                    TransactionDto = new TransactionDto 
                    { 
                         EmployeeName=""
                    }
                }
        );
    }

    [HttpPost]
    public async Task<IActionResult> CreateTransaction(TransactionDto transactionDto)
    {
       await _transactionService.CreateTransactionAsync(transactionDto);

        return Redirect("Index");
    }

}

FinTechApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FinTechApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/FinTechApp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">FinTechApp</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Client">Client</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Transaction" asp-action="Index">Transaction</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="ImageUpload">ImageUpload</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Images">Images</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - FinTechApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>