FinTechApp/Controllers/FileController.cs
namespace FinTechApp.Controllers;

using System;
using System.IO;
using System.Linq;
using FinTech_App.Dto;
using FinTech_App.Model;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

public class FileController : Controller
{
    private readonly ILogger<FileController> _logger;
    private readonly FinTechDbContext _db;
    private readonly IWebHostEnvironment _appEnvironment;

    public FileController(ILogger<FileController> logger, FinTechDbContext db, IWebHostEnvironment appEnvironment)
    {
        _logger = logger;
        _db = db;
        _appEnvironment = appEnvironment;
    }


    public  IActionResult  Index()
    {

        FileModel? file = _db.Files.FirstOrDefault();
        if (file == null)         return View();
        string imgB64 = Convert.ToBase64String(file.FileData);
     

        var filePath = _appEnvironment.WebRootPath + "\\images\\" + file.FileName;

        System.IO.File.WriteAllBytes(filePath, file.FileData);

        FileModelDto fileDto = new FileModelDto
        {
            Base64 = imgB64,
            Name = "\\images\\" + file.FileName
        };
        return View(fileDto);
    }

    [HttpPost]
    public IActionResult UploadFile(IFormFile file)
    {
        if (file != null && file.Length > 0)
        {
            using MemoryStream ms = new();
            file.CopyTo(ms);
            byte[] fileBytes = ms.ToArray();
            var newFile = new FileModel
            {
                FileName = file.FileName,
                FileData = fileBytes
            };
            _db.Files.Add(newFile);
            _db.SaveChanges();
        }

        return RedirectToAction("Index", "Home"); // Redirect to home or wherever you want
    }
}

FinTechApp/Controllers/HomeController.cs
using FinTech_App.Dto;
using FinTech_App.Model;
using FinTechApp.Communication;
using FinTechApp.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using System.Diagnostics;
using System.Security.Policy;

namespace FinTechApp.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly IClientDataService _dataService;
        private readonly FinTechDbContext _db;
        private readonly IWebHostEnvironment _appEnvironment;

        public HomeController(ILogger<HomeController> logger, 
            IClientDataService clientDataService,  FinTechDbContext db, IWebHostEnvironment appEnvironment)
        {
            _logger = logger;
            _dataService = clientDataService;
            _db = db;
            _appEnvironment = appEnvironment;
        }

        public IActionResult Index()
        {
            _logger.Log(LogLevel.Information, "Index was requested");
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        public async Task<IActionResult> Client()
        {
            return View(await _dataService.GetClientsAsync());
        }

        public async Task<IActionResult> aClient(int id)
        {
            return View(await _dataService.GetClientAsync(id));
        }

        public IActionResult CreateClient()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DoCreateClient(Client client) {
            await _dataService.CreateClientAsync(client);
            return RedirectToAction("Client");
        }

        [HttpPost]
        public async Task<IActionResult> DeleteClient(long clientId)
        {
            await _dataService.DeleteClientAsync(clientId);
            return RedirectToAction("Client");
        }

        public IActionResult ImageUpload()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> DoUpload(List<IFormFile> files, string description)
        {
            long size = files.Sum(file => file.Length);
            foreach(var file in files)
            {
                //   var filePath = Path.GetTempFileName();

                var MyConfig = new ConfigurationBuilder().AddJsonFile("appsettings.json").Build();
                var imageDirectory = MyConfig.GetValue<string>("ImageDirectory");
                if (imageDirectory == null) imageDirectory = "c:\\images";

                imageDirectory = _appEnvironment.WebRootPath;

                var filePath = imageDirectory + "\\images\\" + file.FileName;

                using (var stream = System.IO.File.Create(filePath))
                {
                    await file.CopyToAsync(stream);
                }
                _db.Images.Add(new ImageTemplate
                {
                     CreatedDate = DateTime.Now,
                     Description = description,
                     FileName = file.FileName,
                     Path= imageDirectory
                });
                await _db.SaveChangesAsync();

            }

            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Images()
        {
            List<ImageTemplate> images = await _db.Images.ToListAsync();
            return View(images);
        }

 

        public IActionResult Graph()
        {
            List<GraphDataDto> graph = new ()
            {
                new (){   Country="Italy", Size=55 },
                 new (){   Country="France", Size=49 },
                 new (){   Country="Spain", Size=44 },
            };

            return View(graph);
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }



    }
}

FinTechApp/Controllers/ImageController.cs
using Microsoft.AspNetCore.Mvc;
using SkiaSharp;


namespace FinTechApp.Controllers;

public class ImageController : Controller
{
   

    // Install-Package SkiaSharp
    public IActionResult GenerateImageSkia()
    {
        // Create a bitmap object
        using SKBitmap bitmap = new(450, 100);
        // Create a canvas from the bitmap
        using SKCanvas canvas = new(bitmap);
        // Clear the canvas with white color
        canvas.Clear(SKColors.White);
        // Draw a red rectangle on the canvas
        using SKPaint paint = new();
        paint.Color = SKColors.Red;
        canvas.DrawRect(new SKRect(10, 10, 420, 90), paint);
        // Draw text on the canvas
        using SKPaint textPaint = new();
        textPaint.Color = SKColors.White;
        textPaint.TextSize = 26;
        canvas.DrawText("Universal NBG image", 20, 50, textPaint);
        // Encode the bitmap to a PNG image
        using SKImage image = SKImage.FromBitmap(bitmap);
        using SKData data = image.Encode(SKEncodedImageFormat.Png, 100);
        // Get the bytes of the encoded image
        byte[] bytes = data.ToArray();
        // Return the image bytes as a file
        return File(bytes, "image/png");
    }


}

FinTechApp/Views/Home/Client.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@model ICollection<FinTech_App.Model.Client>

<style type="text/css" media="screen">

    #clientTable {
        border-collapse: collapse;
        border: 1px solid #000000;
    }

        #clientTable td, #clientTable th {
            border: 1px solid #000000;
        }
</style>



<h1> Clients</h1>

@if (Model.Count != 0)
{
    <table id="clientTable">
        <tr  ><th>Name</th><th>Email</th><th>DateOfBirth</th><th>Identidier</th><th>Action</th></tr>

        @foreach (var client in Model)
        {
            <tr  >
                <td>@client.Name </td>
                <td>@client.Email </td>             
                <td>@client.DateOfBirth </td>
                <td>@client.Identidier </td>
                <td>
                    <a asp-controller="Home" asp-action="aclient" asp-route-id="@client.Id">Details</a>
                    <form asp-action="DeleteClient">
                        <input type="hidden" name="clientId" asp-for="@client.Id" />
                        <input type="submit" value="Delete" class="btn btn-danger" /> 
                    </form>

                </td>
            </tr>
        }

    </table>
}
else
{
    <p> There are no records!</p>
}
<hr />
<a asp-controller="Home" asp-action="CreateClient">Create Client</a> 

FinTechApp/Views/Home/CreateClient.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<!-- CreateClient-->

<form asp-action="DoCreateClient" >
<table>
        <tr> <td>Name</td> <td><input type="text" id="Name" name="Name" /></td></tr>
        <tr> <td>Email</td> <td><input type="email" id="Email" name="Email" /></td></tr>
        <tr> <td>DateOfBirth</td> <td><input type="date" id="DateOfBirth" name="DateOfBirth" required /></td></tr>
        <tr><td colspan="2"><input type="submit" value="Submit" /></td></tr>
    </table>
</form>

FinTechApp/Views/Home/Graph.cshtml
@using FinTech_App.Dto
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@model List<GraphDataDto>

 
<script src="https://www.gstatic.com/charts/loader.js"></script>

 
<div id="myChart" style="width:100%; max-width:600px; height:500px;"></div>

Type of chart
<Select onchange="drawChart(this.value)">
    <option value="Line" >Line</option>
    <option value="Pie">Pie</option>
    <option value="Bar">Bar</option>
    <option value="Column">Column</option>
    <option value="Scatter">Scatter</option>
    </Select>


<script>
        google.charts.load('current', {'packages':['corechart']});
        google.charts.setOnLoadCallback(drawChart);

    function drawChart(method) {
         var basicData = [
            ['Country', 'Mhl']]


            rawData  =  [  
             ['Italy', 55],
            ['France', 49],
            ['Spain', 44],
            ['USA', 24],
            ['Argentina', 15]
            ];
/**/ //TODO ***
   //     rawData = JsonConvert.SerializeObject(@Model))
        

            rawData.forEach(item => basicData.push(item))
            


        // Set Data
        const data = google.visualization.arrayToDataTable(  basicData);

        // Set Options
        const options = {
          title:'World Wide Wine Production'
        };

        

        // Draw
       // const chart = new google.visualization.LineChart(document.getElementById('myChart'));
      //  chart.draw(data, options);
        switch (method) {

            case "Pie":
                  chart = new google.visualization.PieChart(document.getElementById('myChart'));
                chart.draw(data, options);
                return;
            case "Bar":
                  chart = new google.visualization.BarChart(document.getElementById('myChart'));
                chart.draw(data, options);
                return;
            case "Scatter":
                  chart = new google.visualization.ScatterChart(document.getElementById('myChart'));
                chart.draw(data, options);
                return;
            case "Column":
                  chart = new google.visualization.ColumnChart(document.getElementById('myChart'));
                chart.draw(data, options);
                return;


            case "Line":
            default:
                  chart = new google.visualization.LineChart(document.getElementById('myChart'));
                chart.draw(data, options);
                return;
        }


        }

 
        // Draw
       


    function getData() {
       // url = 
    }



    </script>

 

FinTechApp/Views/Home/ImageUpload.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<form asp-controller="Home" asp-action="DoUpload" enctype="multipart/form-data">
    <input type="file" id="myFile" name="files"  accept="image/*" required><br />
    <input type="text" name="description" placeholder="description" required="required" /><br />
    <input type="submit" value="file upload">
</form>

<hr />

<form asp-action="UploadFile" asp-controller="File" method="post" enctype="multipart/form-data">
    <input type="file" name="file" />
    <button type="submit">Upload</button>
</form>

<a asp-controller="Home"  asp-action="Index">Goto Index</a>

FinTechApp/Views/Home/Images.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@model List<ImageTemplate>

<style>
    #imageData td, th {
        border: 1px solid black;
        padding:6px;
    }

</style>

<h1> Images in database</h1>
@foreach( var item in Model)
{
   <div id="item-div">

        <img src="/images/@item.FileName" width="100px" height="100px" /><br />
        <table id="imageData">
            <tr><th>Id</th><th>FileName</th><th>Description</th><th>CreatedDate</th></tr>
            <tr><td>@item.Id </td><td> @item.FileName.Substring(1,5)</td>
                <td>@item.Description</td>
                <td>@item.CreatedDate</td>
                </tr>
           </table>
     </div>
    <br />
    <hr />
    <br />
}

FinTechApp/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>


<div align="center"><img src="images/im1.jpg" width="200px" height="200px" /></div>

FinTechApp/Views/Home/aClient.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@model FinTech_App.Model.Client


@if (Model != null)
{
    <p> Id = @Model.Id  </p>
    <p> Name = @Model.Name  </p>
    <p> DoB = @Model.DateOfBirth </p>
    <p> Identifier = @Model.Identidier </p>
 
 
}